### ISSUE TITLE
OSGView: Convenient switch between 2D and 3D

### ISSUE THREAD

**Issue by hpuhr** [hpuhr/ATSDB#25]
A more convenient switching method between 2D and 3D (and back) was requested.

Additional information about the actual behaviour is needed.

**Comment by alex-scp** [comment]
the implementation could do something similar to the 2D/3D button in paraview which allows a fast switching between 2D (projection with only x, y and no z) and 3D.
the 2D button could either be a real button, although in this case cluttering the toolbar, or preferably a hot key.

in this case since most use cases are performed in 2D (latitude and longitude) a quick return to the default (2D) view is desirable.

the 3D view allows a better understanding of the height information and of the flight profiles.

**Comment by hpuhr** [comment]
Done in v0.5.3.
