### ISSUE TITLE
issue with the "Connect None" checkbox

### ISSUE THREAD

**Issue by alex-scp** [hpuhr/ATSDB#45]
the Connect None checkbox doesn't remove the lines connecting the trajectories.

the connecting lines, especially the ones in the radar and MLAT reports clutter the image.

**Comment by hpuhr** [comment]
This is a misunderstanding, the "Connect None" checkbox changes if target reports with a NULL altitude are line-connected within the group (or skipped).
I will change the checkbox name to "Connect Height None" and add a "Connect Groups" one which changes if lines are drawn at all.
Since the current behaviour is as expected, I'll reflag it as enhancement.

**Comment by hpuhr** [comment]
Renamed to "Connect Height None" and added a "Connect Groups" one. #46 will be kept open as future enhancement.
